schema_version: 1

context:
  version: "6.4.0"

package:
  name: fastframes
  version: ${{ version }}

source:
  url: https://gitlab.cern.ch/atlas-amglab/fastframes/-/archive/v${{ version }}/fastframes-v${{ version }}.tar.gz
  sha256: 901b4908594a108e5790ebb45cbf695a044c35093d82a757d081adda04e23f2c
  patches:
    - fix-root-6-38-compat.patch
    - install-python-files.patch
    - fix-python-linking.patch
    - fix-missing-tfile-include.patch
    - fix-onnxruntime.patch
    - drop-so-suffix.patch

build:
  number: 0
  skip:
    - win
  script:
    - cmake ${CMAKE_ARGS} -DPython3_EXECUTABLE=$PYTHON -DPython3_INCLUDE_DIR=$PREFIX/include/python${PY_VER} -DFASTFRAMES_PYTHON_INSTALL_DIR=$SP_DIR -DONNXRUNTIME_INCLUDE_DIRS=$PREFIX/include/onnxruntime -DONNXRUNTIME_LIBRARIES=$PREFIX/lib/libonnxruntime.so -S . -B build
    - cmake --build build --clean-first --parallel="${CPU_COUNT}" --verbose
    - cmake --install build

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - make
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
        - root_base
        - root_cxx_standard
  host:
    - root_base
    - root_cxx_standard
    - libboost-python-devel
    - python
    - onnxruntime-cpp
  run:
    - python
    - pyyaml

tests:
  - package_contents:
      files:
        - bin/fast-frames.exe
  - script:
      - FastFrames.py -h

about:
  license: BSD-2-Clause
  license_file: LICENSE
  summary: 'FastFrames: RDataFrames for ATLAS analysis ntuples'
  description: |
    FastFrames is a package aimed at processing ntuples produced by
    TopCPToolkit, or a similar CP algorithm based framework, into histograms or
    ntuples.  FastFrames rely on ROOT's RDataFrame to do the event loop
    processing.  The code allows users to define their own columns in a minimal
    way while using all the functionality of the processing.
  homepage: https://gitlab.cern.ch/atlas-amglab/fastframes
  repository: https://gitlab.cern.ch/atlas-amglab/fastframes
  documentation: https://atlas-project-topreconstruction.web.cern.ch/fastframesdocumentation/latest/

extra:
  recipe-maintainers:
    - p-queue
    - kratsg
